Authetication cleanup
krux/catchpoint-api-python pull request #3
Opened 2016-09-14 00:28 UTC by hanpeter

## What does this PR do?
This PR cleans up how authentication token is handled

## Why is this change being made?
1. Simply failing the API call because authentication token has expired is not acceptable.
1. Passing credentials with every method is not ideal.

## Where should the reviewer start?
`catchpoint.py`

## How was this tested? How can the reviewer verify your testing?
The change was manually tested on development environment.

2016-09-14 19:56 UTC, joestump commented on catchpoint.py
> +        self._token_expires_on = datetime(MINYEAR, 1, 1, tzinfo=pytz.utc)
Why is this a gotcha? Can you include a link or more explanation?

2016-09-14 19:57 UTC, joestump commented on catchpoint.py
> +                self._headers.pop("Authorization")
I feel like `del` is more clear Python for removing a key in a `dict`.

2016-09-14 19:58 UTC, joestump approved these changes
Minor comments, but the code looks good.

2016-09-15 17:21 UTC, plathrop commented on catchpoint.py
> +            # GOTCHA: Take out 60 seconds from the expiry just to be safe
Can you explain this a little better than "just to be safe"? What is the gotcha you experienced here?

2016-09-15 17:23 UTC, plathrop commented on catchpoint.py
> +            self._token_expires_on = now + timedelta(seconds=(int(auth_token["expires_in"]) - 60))
Prefer constants to hardcoded integers. Something like
```python
# At class level
EXPIRATION_SAFETY_MARGIN = 60 # seconds

# Here
self._token_expires_on = now + timedelta(seconds=(int(auth_token["expires_in"]) - EXPIRATION_SAFETY_MARGIN))
```
This accomplishes two things: it makes the code more readable to maintainers (I know what this magic number means now), and it makes it easier to change when this value inevitably finds use elsewhere.

2016-09-15 17:24 UTC, plathrop commented on catchpoint.py
> +        return self._headers
Nit: you called this method `get_header`, but you are returning a *collection* of headers (plural).

2016-09-15 17:25 UTC, plathrop commented on catchpoint.py
> +    def _call(self, url, *args, **kwargs):
Whenever you find yourself accepting `*args, **kwargs` you know immediately that you *must* provide a detailed comment explaining why it was necessary.

2016-09-15 17:25 UTC, plathrop commented on catchpoint.py
> +    def _make_request(self, *args, **kwargs):
Ditto re: `*args, **kwargs`. Also, docstring (yes, even internal methods deserve docstrings).

2016-09-15 17:26 UTC, plathrop requested changes
Looks good overall, but there are a couple cleanup items necessary.

2016-09-15 23:56 UTC, hanpeter commented
@plathrop All your comments should be addressed. There needs to be a full update on docstring and `README.md`, but I didn't want to blow up the scope of this PR. I'll handle that next.

2016-09-16 03:58 UTC, plathrop approved these changes
👍

2016-09-16 21:35 UTC, merged